name: Build and Publish to NuGet

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0.103'
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.NUGET_API_KEY }}

    - uses: nuget/setup-nuget@v1
      with:
        nuget-api-key: ${{ secrets.NUGET_API_KEY }}
        nuget-version: '5.x'

    - name: Restore NuGet packages
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release

    - name: Pack
      run: dotnet pack --no-build --configuration Release

    - name: List Nuget Sources
      run: dotnet nuget list source
      
#    - name: Publish the package to nuget.org
#      run: dotnet nuget push */bin/Release/*.nupkg -k $NUGET_AUTH_TOKEN -s nuget.org
#      env:
#        NUGET_AUTH_TOKEN: ${{ secrets.NUGET_TOKEN }}

    - name: Publish the package to nuget.org
      run: nuget push */bin/Release/*.nupkg
